### ISSUE TITLE
Intermittent error in PrometheusBuilder: thread 'main' panicked at 'attempt to add with overflow'

### ISSUE THREAD

**Issue by danielnelson** [metrics-rs/metrics#230]
After adding the Prometheus Exporter to my project, I now get intermittent failures starting my program.  This occurs maybe once out of 20 times I run the program, which was compiled with the debug profile.

```
thread 'main' panicked at 'attempt to add with overflow', /usr/lib/rust/1.53.0/lib/rustlib/src/rust/library/core/src/num/mod.rs:706:5
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::num::<impl u64>::next_power_of_two
             at /usr/lib/rust/1.53.0/lib/rustlib/src/rust/library/core/src/num/uint_macros.rs:1554:13
   4: quanta::Calibration::adjust_cal_ratio
             at /home/dbn/.cargo/registry/src/github.com-1ecc6299db9ec823/quanta-0.7.2/src/lib.rs:273:25
   5: quanta::Calibration::calibrate
             at /home/dbn/.cargo/registry/src/github.com-1ecc6299db9ec823/quanta-0.7.2/src/lib.rs:227:13
   6: quanta::Clock::new::{{closure}}
             at /home/dbn/.cargo/registry/src/github.com-1ecc6299db9ec823/quanta-0.7.2/src/lib.rs:309:17
   7: once_cell::sync::OnceCell<T>::get_or_init::{{closure}}
             at /home/dbn/.cargo/registry/src/github.com-1ecc6299db9ec823/once_cell-1.8.0/src/lib.rs:938:57
   8: once_cell::imp::OnceCell<T>::initialize::{{closure}}
             at /home/dbn/.cargo/registry/src/github.com-1ecc6299db9ec823/once_cell-1.8.0/src/imp_std.rs:95:19
   9: once_cell::imp::initialize_inner
             at /home/dbn/.cargo/registry/src/github.com-1ecc6299db9ec823/once_cell-1.8.0/src/imp_std.rs:171:31
  10: once_cell::imp::OnceCell<T>::initialize
             at /home/dbn/.cargo/registry/src/github.com-1ecc6299db9ec823/once_cell-1.8.0/src/imp_std.rs:93:9
  11: once_cell::sync::OnceCell<T>::get_or_try_init
             at /home/dbn/.cargo/registry/src/github.com-1ecc6299db9ec823/once_cell-1.8.0/src/lib.rs:978:13
  12: once_cell::sync::OnceCell<T>::get_or_init
             at /home/dbn/.cargo/registry/src/github.com-1ecc6299db9ec823/once_cell-1.8.0/src/lib.rs:938:19
  13: quanta::Clock::new
             at /home/dbn/.cargo/registry/src/github.com-1ecc6299db9ec823/quanta-0.7.2/src/lib.rs:307:31
  14: metrics_exporter_prometheus::builder::PrometheusBuilder::build
             at /home/dbn/.cargo/registry/src/github.com-1ecc6299db9ec823/metrics-exporter-prometheus-0.6.0/src/builder.rs:231:31
  15: xxxxxxxxxxxxxx::xxxxxx::router
             at ./xxxxxxxxxxxxxx/src/xxxxxx.rs:296:20
  16: xxxxxxxxxxxxxx::main
             at ./xxxxxxxxxxxxxx/src/main.rs:91:28
  17: core::ops::function::FnOnce::call_once
             at /usr/lib/rust/1.53.0/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
```

**Comment by tobz** [comment]
@danielnelson Sorry the delayed response.  This is... interesting.  You're actually hit an error that I hypothesized might happen (but should be unlikely): https://github.com/metrics-rs/quanta/blob/main/src/lib.rs#L268

`u64::next_power_of_two` will panic in debug mode, versus returning 0 -- which `quanta` checks for -- when in release mode.

Do you have any more information about the system you're reproducing this on? CPU architecture? Operating system? Desktop vs laptop? Uptime?

**Comment by danielnelson** [comment]
This is on a amd64 Thinkpad X13 laptop running Gentoo, it has a Ryzen processor and a custom kernel config.
```
$ uname -a
Linux alf 5.13.12-gentoo #1 SMP Thu Aug 19 13:45:54 PDT 2021 x86_64 AMD Ryzen 7 PRO 4750U with Radeon Graphics AuthenticAMD GNU/Linux
$ uptime -p
up 2 weeks, 1 day, 9 hours, 28 minutes
```

**Comment by tobz** [comment]
Going to close this as I'm not sure there's enough meaningful action to reproduce it and there hasn't been any activity on the issue in a while.
